name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_conda:
    name: build conda
    runs-on: ubuntu-latest

    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
